git:
  paging:
    colorArgs: always
    pager: delta --dark --paging=never
    externalDiffCommand: difft --color=always
update:
  method: never
gui:
  border: single
  parseEmoji: true
  switchTabsWithPanelJumpKeys: true
  theme:
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
  authorColors:
    "*": "#b4befe"
disableStartupPopups: true
