[mgr]
layout = [1, 4, 3]
linemode = "mtime"
scrolloff = 8
show_hidden = true
show_symlink = true
sort_by = "alphabetical"
sort_dir_first = true
sort_reverse = false
sort_sensitive = false

[preview]
max_height = 1000
max_width = 1000
tab_size = 2

[plugin]
prepend_previewers = [
  { mime = "audio/*", run = "exifaudio" },
  { url = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
  { url = "*.csv", run = 'piper -- bat -p --color=always "$1"' },
  { mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}", run = "ouch" },
  { mime = "application/sqlite3", run = 'piper -- sqlite3 "$1" ".schema --indent"' },
]

append_previewers = [
  { url = "*", run = 'piper -- hexyl --border=none --terminal-width=$w "$1"' },
]

prepend_fetchers = [
  { id = "git", url = "*", run = "git", group = "git" },
  { id = "git", url = "*/", run = "git", group = "git" },
]

[opener]
extract = [
  { run = 'ouch d -y "%*"', desc = "Extract here with ouch", for = "windows" },
  { run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]
