hl.config({ animations = { enabled = true } })

hl.curve("fluent_decel", { type = "bezier", points = { { 0, 0.2 }, { 0.4, 1 } } })
hl.curve("easeOutCirc", { type = "bezier", points = { { 0, 0.55 }, { 0.45, 1 } } })
hl.curve("easeOutCubic", { type = "bezier", points = { { 0.33, 1 }, { 0.68, 1 } } })
hl.curve("fade_curve", { type = "bezier", points = { { 0, 0.55 }, { 0.45, 1 } } })

hl.animation({ leaf = "windowsIn", enabled = false })
hl.animation({ leaf = "windowsOut", enabled = false })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 2, bezier = "fluent_decel", style = "slide" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 4, bezier = "fade_curve" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 4, bezier = "fade_curve" })
hl.animation({ leaf = "fadeSwitch", enabled = false })
hl.animation({ leaf = "fadeShadow", enabled = true, speed = 10, bezier = "easeOutCirc" })
hl.animation({ leaf = "fadeDim", enabled = true, speed = 4, bezier = "fluent_decel" })
hl.animation({ leaf = "border", enabled = true, speed = 2.7, bezier = "easeOutCirc" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 30, bezier = "fluent_decel", style = "once" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 3, bezier = "easeOutCubic", style = "fade" })
