-- Hyprland Lua keybindings.
hl.bind("@MAIN_MOD@ + P", hl.dsp.exec_cmd("sessionizer --desktop"))
hl.bind("@MAIN_MOD@ + CTRL + P", hl.dsp.exec_cmd("machine-ssh --desktop"))
hl.bind("@MAIN_MOD@ + CTRL + T", hl.dsp.exec_cmd("piper-toggle-clipboard"))
hl.bind("@MAIN_MOD@ + CTRL + SHIFT + T", hl.dsp.exec_cmd("piper-stop-reading"))
hl.bind("@MAIN_MOD@ + D", hl.dsp.exec_cmd("@DISCORD@"))
hl.bind("@MAIN_MOD@ + SHIFT + D", hl.dsp.exec_cmd("@DMS@ settings toggleWith displays"))
hl.bind("@MAIN_MOD@ + B", hl.dsp.exec_cmd("zen-beta"))
hl.bind("@MAIN_MOD@ + SHIFT + B", hl.dsp.exec_cmd("bar-visibility cycle"))
hl.bind("@MAIN_MOD@ + E", hl.dsp.exec_cmd("nautilus"))
hl.bind("@MAIN_MOD@ + Space", hl.dsp.window.float())
hl.bind("@MAIN_MOD@ + SHIFT + S", hl.dsp.exec_cmd("spotify"))
hl.bind("@MAIN_MOD@ + Return", hl.dsp.exec_cmd("ghostty +new-window"))
hl.bind("@MAIN_MOD@ + S", hl.dsp.exec_cmd("vicinae toggle"))
hl.bind("@MAIN_MOD@ + CTRL + E", hl.dsp.exec_cmd("vicinae vicinae://extensions/vicinae/search-emojis"))
hl.bind("@MAIN_MOD@ + V", hl.dsp.exec_cmd("vicinae vicinae://launch/clipboard/history"))
hl.bind("@MAIN_MOD@ + M", hl.dsp.exec_cmd("@DMS@ processlist focusOrToggle"))
hl.bind("@MAIN_MOD@ + Escape", hl.dsp.exec_cmd("@DMS@ powermenu toggle"))
hl.bind("@MAIN_MOD@ + A", hl.dsp.exec_cmd("@DMS@ settings focusOrToggle"))
hl.bind("@MAIN_MOD@ + N", hl.dsp.exec_cmd("@DMS@ notifications toggle"))
hl.bind("@MAIN_MOD@ + SHIFT + N", hl.dsp.exec_cmd("gnome-text-editor"))
hl.bind("@MAIN_MOD@ + G", hl.dsp.exec_cmd("@DMS@ lock lock"))
hl.bind("@MAIN_MOD@ + SHIFT + W", hl.dsp.exec_cmd("@DMS@ dash toggle wallpaper"))
hl.bind("@MAIN_MOD@ + W", hl.dsp.exec_cmd("delfin"))
hl.bind("@MAIN_MOD@ + SHIFT + Slash", hl.dsp.exec_cmd("@DMS@ keybinds toggle hyprland"))
hl.bind("CTRL + ALT + Delete", hl.dsp.exec_cmd("@DMS@ processlist focusOrToggle"))
hl.bind("@MAIN_MOD@ + SHIFT + E", hl.dsp.exit())
hl.bind("@MAIN_MOD@ + Q", hl.dsp.window.close())
hl.bind("@MAIN_MOD@ + F", hl.dsp.window.fullscreen({ mode = "maximized" }))
hl.bind("@MAIN_MOD@ + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }))
hl.bind("@MAIN_MOD@ + SHIFT + V", hl.dsp.exec_cmd("hyprctl dispatch cyclenext floating"))
hl.bind("@MAIN_MOD@ + Left", hl.dsp.focus({ direction = "l" }))
hl.bind("@MAIN_MOD@ + Down", hl.dsp.focus({ direction = "d" }))
hl.bind("@MAIN_MOD@ + Up", hl.dsp.focus({ direction = "u" }))
hl.bind("@MAIN_MOD@ + Right", hl.dsp.focus({ direction = "r" }))
hl.bind("@MAIN_MOD@ + H", hl.dsp.focus({ direction = "l" }))
hl.bind("@MAIN_MOD@ + J", hl.dsp.focus({ direction = "d" }))
hl.bind("@MAIN_MOD@ + K", hl.dsp.focus({ direction = "u" }))
hl.bind("@MAIN_MOD@ + L", hl.dsp.focus({ direction = "r" }))
hl.bind("@MAIN_MOD@ + SHIFT + Left", hl.dsp.window.move({ direction = "l" }))
hl.bind("@MAIN_MOD@ + SHIFT + Down", hl.dsp.window.move({ direction = "d" }))
hl.bind("@MAIN_MOD@ + SHIFT + Up", hl.dsp.window.move({ direction = "u" }))
hl.bind("@MAIN_MOD@ + SHIFT + Right", hl.dsp.window.move({ direction = "r" }))
hl.bind("@MAIN_MOD@ + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind("@MAIN_MOD@ + SHIFT + J", hl.dsp.window.move({ direction = "d" }))
hl.bind("@MAIN_MOD@ + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind("@MAIN_MOD@ + SHIFT + L", hl.dsp.window.move({ direction = "r" }))
hl.bind("@MAIN_MOD@ + CTRL + Left", hl.dsp.focus({ monitor = "l" }))
hl.bind("@MAIN_MOD@ + CTRL + Right", hl.dsp.focus({ monitor = "r" }))
hl.bind("@MAIN_MOD@ + CTRL + Up", hl.dsp.focus({ monitor = "d" }))
hl.bind("@MAIN_MOD@ + CTRL + Down", hl.dsp.focus({ monitor = "u" }))
hl.bind("@MAIN_MOD@ + CTRL + H", hl.dsp.focus({ monitor = "l" }))
hl.bind("@MAIN_MOD@ + CTRL + J", hl.dsp.focus({ monitor = "d" }))
hl.bind("@MAIN_MOD@ + CTRL + K", hl.dsp.focus({ monitor = "u" }))
hl.bind("@MAIN_MOD@ + CTRL + L", hl.dsp.focus({ monitor = "r" }))
hl.bind("@MAIN_MOD@ + CTRL + SHIFT + Left", hl.dsp.window.move({ monitor = "l" }))
hl.bind("@MAIN_MOD@ + CTRL + SHIFT + Down", hl.dsp.window.move({ monitor = "d" }))
hl.bind("@MAIN_MOD@ + CTRL + SHIFT + Up", hl.dsp.window.move({ monitor = "u" }))
hl.bind("@MAIN_MOD@ + CTRL + SHIFT + Right", hl.dsp.window.move({ monitor = "r" }))
hl.bind("@MAIN_MOD@ + CTRL + SHIFT + H", hl.dsp.window.move({ monitor = "l" }))
hl.bind("@MAIN_MOD@ + CTRL + SHIFT + J", hl.dsp.window.move({ monitor = "d" }))
hl.bind("@MAIN_MOD@ + CTRL + SHIFT + K", hl.dsp.window.move({ monitor = "u" }))
hl.bind("@MAIN_MOD@ + CTRL + SHIFT + L", hl.dsp.window.move({ monitor = "r" }))
hl.bind("@MAIN_MOD@ + Comma", hl.dsp.workspace.move({ monitor = "l" }))
hl.bind("@MAIN_MOD@ + Period", hl.dsp.workspace.move({ monitor = "r" }))
hl.bind("@MAIN_MOD@ + Page_Down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("@MAIN_MOD@ + Page_Up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("@MAIN_MOD@ + U", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("@MAIN_MOD@ + I", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("@MAIN_MOD@ + CTRL + U", hl.dsp.window.move({ workspace = "e+1", follow = true }))
hl.bind("@MAIN_MOD@ + CTRL + I", hl.dsp.window.move({ workspace = "e-1", follow = true }))
hl.bind("@MAIN_MOD@ + SHIFT + Page_Down", hl.dsp.window.move({ workspace = "e+1", follow = true }))
hl.bind("@MAIN_MOD@ + SHIFT + Page_Up", hl.dsp.window.move({ workspace = "e-1", follow = true }))
hl.bind("@MAIN_MOD@ + SHIFT + U", hl.dsp.window.move({ workspace = "e+1", follow = true }))
hl.bind("@MAIN_MOD@ + SHIFT + I", hl.dsp.window.move({ workspace = "e-1", follow = true }))
hl.bind("CTRL + SHIFT + R", hl.dsp.exec_cmd("@DMS@ workspace-rename open"))
hl.bind("@MAIN_MOD@ + 1", hl.dsp.focus({ workspace = "1" }))
hl.bind("@MAIN_MOD@ + 2", hl.dsp.focus({ workspace = "2" }))
hl.bind("@MAIN_MOD@ + 3", hl.dsp.focus({ workspace = "3" }))
hl.bind("@MAIN_MOD@ + 4", hl.dsp.focus({ workspace = "4" }))
hl.bind("@MAIN_MOD@ + 5", hl.dsp.focus({ workspace = "5" }))
hl.bind("@MAIN_MOD@ + 6", hl.dsp.focus({ workspace = "6" }))
hl.bind("@MAIN_MOD@ + 7", hl.dsp.focus({ workspace = "7" }))
hl.bind("@MAIN_MOD@ + 8", hl.dsp.focus({ workspace = "8" }))
hl.bind("@MAIN_MOD@ + 9", hl.dsp.focus({ workspace = "9" }))
hl.bind("@MAIN_MOD@ + SHIFT + 1", hl.dsp.window.move({ workspace = "1", follow = true }))
hl.bind("@MAIN_MOD@ + SHIFT + 2", hl.dsp.window.move({ workspace = "2", follow = true }))
hl.bind("@MAIN_MOD@ + SHIFT + 3", hl.dsp.window.move({ workspace = "3", follow = true }))
hl.bind("@MAIN_MOD@ + SHIFT + 4", hl.dsp.window.move({ workspace = "4", follow = true }))
hl.bind("@MAIN_MOD@ + SHIFT + 5", hl.dsp.window.move({ workspace = "5", follow = true }))
hl.bind("@MAIN_MOD@ + SHIFT + 6", hl.dsp.window.move({ workspace = "6", follow = true }))
hl.bind("@MAIN_MOD@ + SHIFT + 7", hl.dsp.window.move({ workspace = "7", follow = true }))
hl.bind("@MAIN_MOD@ + SHIFT + 8", hl.dsp.window.move({ workspace = "8", follow = true }))
hl.bind("@MAIN_MOD@ + SHIFT + 9", hl.dsp.window.move({ workspace = "9", follow = true }))
hl.bind("@MAIN_MOD@ + R", hl.dsp.layout("togglesplit"))
hl.bind("@MAIN_MOD@ + CTRL + F", hl.dsp.window.fullscreen({ mode = "maximized" }))
hl.bind("@MAIN_MOD@ + Minus", hl.dsp.window.resize({ x = -100, y = 0, relative = true }))
hl.bind("@MAIN_MOD@ + Equal", hl.dsp.window.resize({ x = 100, y = 0, relative = true }))
hl.bind("@MAIN_MOD@ + SHIFT + Minus", hl.dsp.window.resize({ x = 0, y = -100, relative = true }))
hl.bind("@MAIN_MOD@ + SHIFT + Equal", hl.dsp.window.resize({ x = 0, y = 100, relative = true }))
hl.bind("Print", hl.dsp.exec_cmd("dms screenshot"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd("dms screenshot full"))
hl.bind("ALT + Print", hl.dsp.exec_cmd("dms screenshot window"))
hl.bind("XF86Launch1", hl.dsp.exec_cmd("dms screenshot"))
hl.bind("CTRL + XF86Launch1", hl.dsp.exec_cmd("dms screenshot full"))
hl.bind("ALT + XF86Launch1", hl.dsp.exec_cmd("dms screenshot window"))
hl.bind("@MAIN_MOD@ + O", hl.dsp.exec_cmd("ocr"))
hl.bind("@MAIN_MOD@ + SHIFT + O", hl.dsp.exec_cmd("qr-capture"))
hl.bind("@MAIN_MOD@ + SHIFT + P", hl.dsp.dpms({ action = "toggle" }))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("@DMS@ audio mute"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("@DMS@ audio micmute"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("@DMS@ mpris playPause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("@DMS@ mpris playPause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("@DMS@ mpris previous"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("@DMS@ mpris next"), { locked = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("@DMS@ audio increment 2"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("@DMS@ audio decrement 2"), { locked = true, repeating = true })
hl.bind("CTRL + XF86AudioRaiseVolume", hl.dsp.exec_cmd("@DMS@ mpris increment 2"), { locked = true, repeating = true })
hl.bind("CTRL + XF86AudioLowerVolume", hl.dsp.exec_cmd("@DMS@ mpris decrement 2"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("@DMS@ brightness increment 5 ''"), { locked = true, repeating = true })
hl.bind(
	"XF86MonBrightnessDown",
	hl.dsp.exec_cmd("@DMS@ brightness decrement 5 ''"),
	{ locked = true, repeating = true }
)
hl.bind("@MAIN_MOD@ + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("@MAIN_MOD@ + mouse:273", hl.dsp.window.resize(), { mouse = true })
