local variables = require("variables")
local dms = "dms ipc call"

-- Hyprland Lua keybindings.
hl.bind(variables.main_mod .. " + P", hl.dsp.exec_cmd("sessionizer --desktop"))
hl.bind(variables.main_mod .. " + CTRL + P", hl.dsp.exec_cmd("machine-ssh --desktop"))
hl.bind(variables.main_mod .. " + CTRL + T", hl.dsp.exec_cmd("piper-toggle-clipboard"))
hl.bind(variables.main_mod .. " + CTRL + SHIFT + T", hl.dsp.exec_cmd("piper-stop-reading"))
hl.bind(variables.main_mod .. " + D", hl.dsp.exec_cmd(variables.discord))
hl.bind(variables.main_mod .. " + SHIFT + D", hl.dsp.exec_cmd(dms .. " settings toggleWith displays"))
hl.bind(variables.main_mod .. " + B", hl.dsp.exec_cmd("zen-beta"))
hl.bind(variables.main_mod .. " + SHIFT + B", hl.dsp.exec_cmd("bar-visibility cycle"))
hl.bind(variables.main_mod .. " + E", hl.dsp.exec_cmd("nautilus"))
hl.bind(variables.main_mod .. " + Space", hl.dsp.window.float())
hl.bind(variables.main_mod .. " + SHIFT + S", hl.dsp.exec_cmd("spotify"))
hl.bind(variables.main_mod .. " + Return", hl.dsp.exec_cmd("ghostty +new-window"))
hl.bind(variables.main_mod .. " + S", hl.dsp.exec_cmd("vicinae toggle"))
hl.bind(variables.main_mod .. " + CTRL + E", hl.dsp.exec_cmd("vicinae vicinae://extensions/vicinae/search-emojis"))
hl.bind(variables.main_mod .. " + V", hl.dsp.exec_cmd("vicinae vicinae://launch/clipboard/history"))
hl.bind(variables.main_mod .. " + M", hl.dsp.exec_cmd(dms .. " processlist focusOrToggle"))
hl.bind(variables.main_mod .. " + Escape", hl.dsp.exec_cmd(dms .. " powermenu toggle"))
hl.bind(variables.main_mod .. " + A", hl.dsp.exec_cmd(dms .. " settings focusOrToggle"))
hl.bind(variables.main_mod .. " + N", hl.dsp.exec_cmd(dms .. " notifications toggle"))
hl.bind(variables.main_mod .. " + SHIFT + N", hl.dsp.exec_cmd("gnome-text-editor"))
hl.bind(variables.main_mod .. " + G", hl.dsp.exec_cmd(dms .. " lock lock"))
hl.bind(variables.main_mod .. " + SHIFT + W", hl.dsp.exec_cmd(dms .. " dash toggle wallpaper"))
hl.bind(variables.main_mod .. " + W", hl.dsp.exec_cmd("delfin"))
hl.bind(variables.main_mod .. " + SHIFT + Slash", hl.dsp.exec_cmd(dms .. " keybinds toggle hyprland"))
hl.bind("CTRL + ALT + Delete", hl.dsp.exec_cmd(dms .. " processlist focusOrToggle"))
hl.bind(variables.main_mod .. " + SHIFT + E", hl.dsp.exit())
hl.bind(variables.main_mod .. " + Q", hl.dsp.window.close())
hl.bind(variables.main_mod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized" }))
hl.bind(variables.main_mod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }))
hl.bind(variables.main_mod .. " + SHIFT + V", hl.dsp.exec_cmd("hyprctl dispatch cyclenext floating"))
hl.bind(variables.main_mod .. " + Left", hl.dsp.focus({ direction = "l" }))
hl.bind(variables.main_mod .. " + Down", hl.dsp.focus({ direction = "d" }))
hl.bind(variables.main_mod .. " + Up", hl.dsp.focus({ direction = "u" }))
hl.bind(variables.main_mod .. " + Right", hl.dsp.focus({ direction = "r" }))
hl.bind(variables.main_mod .. " + H", hl.dsp.focus({ direction = "l" }))
hl.bind(variables.main_mod .. " + J", hl.dsp.focus({ direction = "d" }))
hl.bind(variables.main_mod .. " + K", hl.dsp.focus({ direction = "u" }))
hl.bind(variables.main_mod .. " + L", hl.dsp.focus({ direction = "r" }))
hl.bind(variables.main_mod .. " + SHIFT + Left", hl.dsp.window.move({ direction = "l" }))
hl.bind(variables.main_mod .. " + SHIFT + Down", hl.dsp.window.move({ direction = "d" }))
hl.bind(variables.main_mod .. " + SHIFT + Up", hl.dsp.window.move({ direction = "u" }))
hl.bind(variables.main_mod .. " + SHIFT + Right", hl.dsp.window.move({ direction = "r" }))
hl.bind(variables.main_mod .. " + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind(variables.main_mod .. " + SHIFT + J", hl.dsp.window.move({ direction = "d" }))
hl.bind(variables.main_mod .. " + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind(variables.main_mod .. " + SHIFT + L", hl.dsp.window.move({ direction = "r" }))
hl.bind(variables.main_mod .. " + CTRL + Left", hl.dsp.focus({ monitor = "l" }))
hl.bind(variables.main_mod .. " + CTRL + Right", hl.dsp.focus({ monitor = "r" }))
hl.bind(variables.main_mod .. " + CTRL + Up", hl.dsp.focus({ monitor = "d" }))
hl.bind(variables.main_mod .. " + CTRL + Down", hl.dsp.focus({ monitor = "u" }))
hl.bind(variables.main_mod .. " + CTRL + H", hl.dsp.focus({ monitor = "l" }))
hl.bind(variables.main_mod .. " + CTRL + J", hl.dsp.focus({ monitor = "d" }))
hl.bind(variables.main_mod .. " + CTRL + K", hl.dsp.focus({ monitor = "u" }))
hl.bind(variables.main_mod .. " + CTRL + L", hl.dsp.focus({ monitor = "r" }))
hl.bind(variables.main_mod .. " + CTRL + SHIFT + Left", hl.dsp.window.move({ monitor = "l" }))
hl.bind(variables.main_mod .. " + CTRL + SHIFT + Down", hl.dsp.window.move({ monitor = "d" }))
hl.bind(variables.main_mod .. " + CTRL + SHIFT + Up", hl.dsp.window.move({ monitor = "u" }))
hl.bind(variables.main_mod .. " + CTRL + SHIFT + Right", hl.dsp.window.move({ monitor = "r" }))
hl.bind(variables.main_mod .. " + CTRL + SHIFT + H", hl.dsp.window.move({ monitor = "l" }))
hl.bind(variables.main_mod .. " + CTRL + SHIFT + J", hl.dsp.window.move({ monitor = "d" }))
hl.bind(variables.main_mod .. " + CTRL + SHIFT + K", hl.dsp.window.move({ monitor = "u" }))
hl.bind(variables.main_mod .. " + CTRL + SHIFT + L", hl.dsp.window.move({ monitor = "r" }))
hl.bind(variables.main_mod .. " + Comma", hl.dsp.workspace.move({ monitor = "l" }))
hl.bind(variables.main_mod .. " + Period", hl.dsp.workspace.move({ monitor = "r" }))
hl.bind(variables.main_mod .. " + Page_Down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(variables.main_mod .. " + Page_Up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(variables.main_mod .. " + U", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(variables.main_mod .. " + I", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(variables.main_mod .. " + CTRL + U", hl.dsp.window.move({ workspace = "e+1", follow = true }))
hl.bind(variables.main_mod .. " + CTRL + I", hl.dsp.window.move({ workspace = "e-1", follow = true }))
hl.bind(variables.main_mod .. " + SHIFT + Page_Down", hl.dsp.window.move({ workspace = "e+1", follow = true }))
hl.bind(variables.main_mod .. " + SHIFT + Page_Up", hl.dsp.window.move({ workspace = "e-1", follow = true }))
hl.bind(variables.main_mod .. " + SHIFT + U", hl.dsp.window.move({ workspace = "e+1", follow = true }))
hl.bind(variables.main_mod .. " + SHIFT + I", hl.dsp.window.move({ workspace = "e-1", follow = true }))
hl.bind("CTRL + SHIFT + R", hl.dsp.exec_cmd(dms .. " workspace-rename open"))
hl.bind(variables.main_mod .. " + 1", hl.dsp.focus({ workspace = "1" }))
hl.bind(variables.main_mod .. " + 2", hl.dsp.focus({ workspace = "2" }))
hl.bind(variables.main_mod .. " + 3", hl.dsp.focus({ workspace = "3" }))
hl.bind(variables.main_mod .. " + 4", hl.dsp.focus({ workspace = "4" }))
hl.bind(variables.main_mod .. " + 5", hl.dsp.focus({ workspace = "5" }))
hl.bind(variables.main_mod .. " + 6", hl.dsp.focus({ workspace = "6" }))
hl.bind(variables.main_mod .. " + 7", hl.dsp.focus({ workspace = "7" }))
hl.bind(variables.main_mod .. " + 8", hl.dsp.focus({ workspace = "8" }))
hl.bind(variables.main_mod .. " + 9", hl.dsp.focus({ workspace = "9" }))
hl.bind(variables.main_mod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = "1", follow = true }))
hl.bind(variables.main_mod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = "2", follow = true }))
hl.bind(variables.main_mod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = "3", follow = true }))
hl.bind(variables.main_mod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = "4", follow = true }))
hl.bind(variables.main_mod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = "5", follow = true }))
hl.bind(variables.main_mod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = "6", follow = true }))
hl.bind(variables.main_mod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = "7", follow = true }))
hl.bind(variables.main_mod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = "8", follow = true }))
hl.bind(variables.main_mod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = "9", follow = true }))
hl.bind(variables.main_mod .. " + R", hl.dsp.layout("togglesplit"))
hl.bind(variables.main_mod .. " + CTRL + F", hl.dsp.window.fullscreen({ mode = "maximized" }))
hl.bind(variables.main_mod .. " + Minus", hl.dsp.window.resize({ x = -100, y = 0, relative = true }))
hl.bind(variables.main_mod .. " + Equal", hl.dsp.window.resize({ x = 100, y = 0, relative = true }))
hl.bind(variables.main_mod .. " + SHIFT + Minus", hl.dsp.window.resize({ x = 0, y = -100, relative = true }))
hl.bind(variables.main_mod .. " + SHIFT + Equal", hl.dsp.window.resize({ x = 0, y = 100, relative = true }))
hl.bind("Print", hl.dsp.exec_cmd("dms screenshot"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd("dms screenshot full"))
hl.bind("ALT + Print", hl.dsp.exec_cmd("dms screenshot window"))
hl.bind("XF86Launch1", hl.dsp.exec_cmd("dms screenshot"))
hl.bind("CTRL + XF86Launch1", hl.dsp.exec_cmd("dms screenshot full"))
hl.bind("ALT + XF86Launch1", hl.dsp.exec_cmd("dms screenshot window"))
hl.bind(variables.main_mod .. " + O", hl.dsp.exec_cmd("ocr"))
hl.bind(variables.main_mod .. " + SHIFT + O", hl.dsp.exec_cmd("qr-capture"))
hl.bind(variables.main_mod .. " + SHIFT + P", hl.dsp.dpms({ action = "toggle" }))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd(dms .. " audio mute"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd(dms .. " audio micmute"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd(dms .. " mpris playPause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd(dms .. " mpris playPause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd(dms .. " mpris previous"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd(dms .. " mpris next"), { locked = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd(dms .. " audio increment 2"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd(dms .. " audio decrement 2"), { locked = true, repeating = true })
hl.bind(
	"CTRL + XF86AudioRaiseVolume",
	hl.dsp.exec_cmd(dms .. " mpris increment 2"),
	{ locked = true, repeating = true }
)
hl.bind(
	"CTRL + XF86AudioLowerVolume",
	hl.dsp.exec_cmd(dms .. " mpris decrement 2"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86MonBrightnessUp",
	hl.dsp.exec_cmd(dms .. " brightness increment 5 ''"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86MonBrightnessDown",
	hl.dsp.exec_cmd(dms .. " brightness decrement 5 ''"),
	{ locked = true, repeating = true }
)
hl.bind(variables.main_mod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(variables.main_mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
