-- Hyprland Lua window and workspace rules.
hl.window_rule({ match = { class = "^(audacious)$" }, float = true })
hl.window_rule({ match = { class = "^(waypaper)$" }, pin = true })
hl.window_rule({ match = { class = "^(org.pulseaudio.pavucontrol)$" }, float = true })
hl.window_rule({ match = { class = "^(org.pulseaudio.pavucontrol)$" }, size = { 1200, 725 } })
hl.window_rule({ match = { class = "^(org.pulseaudio.pavucontrol)$" }, center = true })
hl.window_rule({ match = { class = "^(com.interversehq.qView)$" }, float = true })
hl.window_rule({ match = { class = "^(com.interversehq.qView)$" }, center = true })
hl.window_rule({ match = { class = "^(com.interversehq.qView)$" }, size = { 1200, 725 } })
hl.window_rule({ match = { class = "^(nwg-displays)$" }, float = true })
hl.window_rule({ match = { class = "^(nwg-displays)$" }, size = { 1200, 725 } })
hl.window_rule({ match = { class = "^(nwg-displays)$" }, center = true })
hl.window_rule({ match = { class = "^(mpv)$" }, float = true })
hl.window_rule({ match = { class = "^(mpv)$" }, center = true })
hl.window_rule({ match = { class = "^(mpv)$" }, size = { 1200, 725 } })
hl.window_rule({ match = { class = "^(mpv|.+exe|celluloid)$" }, idle_inhibit = "focus" })
hl.window_rule({ match = { class = "^(zen)$", title = "^(.*YouTube.*)$" }, idle_inhibit = "focus" })
hl.window_rule({ match = { class = "^(zen)$" }, idle_inhibit = "fullscreen" })
hl.window_rule({ match = { workspace = "w[t1]", float = false }, border_size = 0 })
hl.window_rule({ match = { workspace = "w[t1]", float = false }, rounding = 0 })
hl.window_rule({ match = { workspace = "w[t1]", float = false }, border_size = 0 })
hl.window_rule({ match = { workspace = "w[t1]", float = false }, rounding = 0 })
hl.window_rule({ match = { workspace = "f[1]", float = false }, border_size = 0 })
hl.window_rule({ match = { workspace = "f[1]", float = false }, rounding = 0 })
hl.window_rule({ match = { title = "^(Picture-in-Picture)$" }, float = true })
hl.window_rule({ match = { title = "^(Picture-in-Picture)$" }, opacity = "1.0 override" })
hl.window_rule({ match = { title = "^(Picture-in-Picture)$" }, pin = true })
hl.window_rule({ match = { title = "^(.*mpv.*)$" }, opacity = "1.0 override" })
hl.window_rule({ match = { class = "^(mpv)$" }, idle_inhibit = "focus" })
hl.window_rule({ match = { class = "^(firefox)$" }, idle_inhibit = "fullscreen" })
hl.window_rule({ match = { class = "^(org.gnome.FileRoller)$" }, float = true })
hl.window_rule({ match = { class = "^(org.pulseaudio.pavucontrol)$" }, float = true })
hl.window_rule({ match = { class = "^(.sameboy-wrapped)$" }, float = true })
hl.window_rule({ match = { class = "^(file_progress)$" }, float = true })
hl.window_rule({ match = { class = "^(confirm)$" }, float = true })
hl.window_rule({ match = { class = "^(dialog)$" }, float = true })
hl.window_rule({ match = { class = "^(download)$" }, float = true })
hl.window_rule({ match = { class = "^(notification)$" }, float = true })
hl.window_rule({ match = { class = "^(error)$" }, float = true })
hl.window_rule({ match = { class = "^(confirmreset)$" }, float = true })
hl.window_rule({ match = { title = "^(.*Open File.*)$" }, float = true })
hl.window_rule({ match = { title = "^(.*File Upload.*)$" }, float = true })
hl.window_rule({ match = { title = "^(branchdialog)$" }, float = true })
hl.window_rule({ match = { title = "^(Confirm to replace files)$" }, float = true })
hl.window_rule({ match = { title = "^(File Operation Progress)$" }, float = true })
hl.window_rule({ match = { title = "^(.*Bitwarden Password Manager.*)$" }, float = true })
hl.window_rule({ match = { title = "^(Firefox — Sharing Indicator)$" }, workspace = "special silent" })
hl.window_rule({ match = { title = "^(Zen — Sharing Indicator)$" }, workspace = "special silent" })
hl.window_rule({ match = { title = "^(.*is sharing (your screen|a window)\\.)$" }, workspace = "special silent" })
hl.window_rule({ match = { class = "^(xwaylandvideobridge)$" }, opacity = "0.0 override" })
hl.window_rule({ match = { class = "^(xwaylandvideobridge)$" }, no_anim = true })
hl.window_rule({ match = { class = "^(xwaylandvideobridge)$" }, no_initial_focus = true })
hl.window_rule({ match = { class = "^(xwaylandvideobridge)$" }, max_size = { 1, 1 } })
hl.window_rule({ match = { class = "^(xwaylandvideobridge)$" }, no_blur = true })
hl.window_rule({ match = { class = "^(zen-beta)$" }, workspace = "1" })
hl.window_rule({ match = { class = "^(gimp)$" }, workspace = "4" })
hl.window_rule({ match = { class = "^(Audacious)$" }, workspace = "5" })
hl.window_rule({ match = { class = "^(@DISCORD@)$" }, workspace = "5" })
hl.window_rule({ match = { class = "^(Spotify)$" }, workspace = "6" })
hl.window_rule({ match = { class = "^(com.obsproject.Studio)$" }, workspace = "8" })
hl.window_rule({ match = { float = true }, border_size = 0 })
hl.window_rule({ match = { class = "^()$", title = "^()$" }, opaque = true })
hl.window_rule({ match = { class = "^()$", title = "^()$" }, no_shadow = true })
hl.window_rule({ match = { class = "^()$", title = "^()$" }, no_blur = true })

hl.workspace_rule({ workspace = "3", layout = "scrolling" })
hl.workspace_rule({ workspace = "4", layout = "scrolling" })
hl.workspace_rule({ workspace = "5", layout = "scrolling" })
hl.workspace_rule({ workspace = "6", layout = "scrolling" })
hl.workspace_rule({ workspace = "w[t1]", gaps_out = 0, gaps_in = 0 })
hl.workspace_rule({ workspace = "w[tg1]", gaps_out = 0, gaps_in = 0 })
hl.workspace_rule({ workspace = "f[1]", gaps_out = 0, gaps_in = 0 })
