[mgr]

prepend_keymap = [
  # Goto
  { on = [
    "g",
    "D",
  ], run = "cd ~/Documents", desc = "Go ~/Documents" },
  { on = [
    "g",
    "p",
  ], run = "cd ~/Projects", desc = "Go ~/Projects" },
  { on = [
    "g",
    "l",
  ], run = "cd ~/.local", desc = "Go ~/.local" },
  { on = [
    "g",
    "s",
  ], run = "cd ~/.ssh", desc = "Go ~/.ssh" },
  { on = [
    "g",
    "m",
  ], run = "cd /mnt", desc = "Go /mnt" },
  { on = [
    "g",
    "o",
  ], run = "cd /opt", desc = "Go /opt" },
  { on = [
    "g",
    "M",
  ], run = "cd ~/Music", desc = "Go ~/Music" },
  { on = [
    "g",
    "P",
  ], run = "cd ~/Pictures", desc = "Go ~/Pictures" },
  { on = [
    "g",
    "v",
  ], run = "cd ~/Videos", desc = "Go ~/Videos" },
  { on = [
    "g",
    "t",
  ], run = "cd ~/.local/share/Trash/files", desc = "Go ~/.local/share/Trash/files" },

  # Search
  { on = "Z", run = "plugin fzf", desc = "Jump to a file/directory via fzf" },
  { on = "z", run = "plugin zoxide", desc = "Jump to a directory via zoxide" },

  # Plugins
  { on = [
    "c",
    "m",
  ], run = "plugin chmod", desc = "Chmod on selected files" },
  { on = "<C-d>", run = "plugin diff", desc = "Diff the selected with the hovered file" },
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
  { on = "C", run = "plugin ouch", desc = "Compress with ouch" },
  { on = "<C-e>", run = "seek 5", desc = "Seek forward 5" },
  { on = "<C-q>", run = "seek -5", desc = "Seek backward 5" },
  { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
  { on = "M", run = "plugin mount", desc = "Open the mount menu" },
  { on = [
    "c",
    "i",
  ], run = "plugin system-clipboard", desc = "Copy the file" },
  { on = [
    "c",
    "o",
  ], run = "plugin copy-file-contents", desc = "Copy contents of file" },
  { on = [
    "g",
    "i",
  ], run = "plugin lazygit", desc = "Open lazygit" },

  # Toggle pane
  { on = "e", run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane" },
  { on = "E", run = "plugin toggle-pane min-preview", desc = "Show or hide the preview pane" },
  { on = "T", run = "plugin toggle-pane min-parent", desc = "Show or hide the parent pane" },

  # Relative motions
  { on = "1", run = "plugin relative-motions 1", desc = "Move in relative steps" },
  { on = "2", run = "plugin relative-motions 2", desc = "Move in relative steps" },
  { on = "3", run = "plugin relative-motions 3", desc = "Move in relative steps" },
  { on = "4", run = "plugin relative-motions 4", desc = "Move in relative steps" },
  { on = "5", run = "plugin relative-motions 5", desc = "Move in relative steps" },
  { on = "6", run = "plugin relative-motions 6", desc = "Move in relative steps" },
  { on = "7", run = "plugin relative-motions 7", desc = "Move in relative steps" },
  { on = "8", run = "plugin relative-motions 8", desc = "Move in relative steps" },
  { on = "9", run = "plugin relative-motions 9", desc = "Move in relative steps" },

  # Tabs
  { on = [
    "t",
    "c",
  ], run = "tab_create --current", desc = "Create a new tab with CWD" },
  { on = [
    "t",
    "x",
  ], run = "close", desc = "Close the current tab, or quit if it's last" },

  { on = [
    "t",
    "1",
  ], run = "tab_switch 0", desc = "Switch to first tab" },
  { on = [
    "t",
    "2",
  ], run = "tab_switch 1", desc = "Switch to second tab" },
  { on = [
    "t",
    "3",
  ], run = "tab_switch 2", desc = "Switch to third tab" },
  { on = [
    "t",
    "4",
  ], run = "tab_switch 3", desc = "Switch to fourth tab" },
  { on = [
    "t",
    "5",
  ], run = "tab_switch 4", desc = "Switch to fifth tab" },
  { on = [
    "t",
    "6",
  ], run = "tab_switch 5", desc = "Switch to sixth tab" },
  { on = [
    "t",
    "7",
  ], run = "tab_switch 6", desc = "Switch to seventh tab" },
  { on = [
    "t",
    "8",
  ], run = "tab_switch 7", desc = "Switch to eighth tab" },
  { on = [
    "t",
    "9",
  ], run = "tab_switch 8", desc = "Switch to ninth tab" },
  { on = [
    "t",
    "0",
  ], run = "tab_switch 9", desc = "Switch to tenth tab" },
]

[spot]
prepend_keymap = [{ on = "q", run = "close", desc = "Close the spot" }]

[pick]
prepend_keymap = [{ on = "q", run = "close", desc = "Cancel pick" }]

[tasks]
prepend_keymap = [{ on = "q", run = "close", desc = "Close task manager" }]

[confirm]
prepend_keymap = [{ on = "q", run = "close", desc = "Cancel the confirm" }]

[help]
prepend_keymap = [{ on = "q", run = "close", desc = "Hide the help" }]
