[manager]

keymap = [
  # Goto
  { on = [
    "g",
    "h",
  ], run = "cd ~", desc = "Go home" },
  { on = [
    "g",
    "c",
  ], run = "cd ~/.config", desc = "Go ~/.config" },
  { on = [
    "g",
    "d",
  ], run = "cd ~/Downloads", desc = "Go ~/Downloads" },
  { on = [
    "g",
    "D",
  ], run = "cd ~/Documents", desc = "Go ~/Documents" },
  { on = [
    "g",
    "p",
  ], run = "cd ~/Projects", desc = "Go ~/Projects" },
  { on = [
    "g",
    "l",
  ], run = "cd ~/.local", desc = "Go ~/.local" },
  { on = [
    "g",
    "s",
  ], run = "cd ~/.ssh", desc = "Go ~/.ssh" },
  { on = [
    "g",
    "m",
  ], run = "cd ~/Music", desc = "Go ~/Music" },
  { on = [
    "g",
    "P",
  ], run = "cd ~/Pictures", desc = "Go ~/Pictures" },
  { on = [
    "g",
    "v",
  ], run = "cd ~/Videos", desc = "Go ~/Videos" },
  { on = [
    "g",
    "t",
  ], run = "cd ~/.local/share/Trash/files", desc = "Go ~/.local/share/Trash/files" },
  { on = [
    "g",
    "<Space>",
  ], run = "cd --interactive", desc = "Jump interactively" },
  { on = [
    "g",
    "f",
  ], run = "follow", desc = "Follow hovered symlink" },

  # Search
  { on = "Z", run = "plugin fzf", desc = "Jump to a file/directory via fzf" },
  { on = "z", run = "plugin zoxide", desc = "Jump to a directory via zoxide" },

  # Plugins
  { on = [
    "c",
    "m",
  ], run = "plugin chmod", desc = "Chmod on selected files" },
  { on = "<C-d>", run = "plugin diff", desc = "Diff the selected with the hovered file" },
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
  { on = "<A-y>", run = "plugin copy-file-contents", desc = "Copy contents of file" },
  { on = "C", run = "plugin ouch", desc = "Compress with ouch" },
  { on = "<C-e>", run = "seek 5", desc = "Seek forward 5" },
  { on = "<C-y>", run = "seek -5", desc = "Seek backward 5" },
]
