[manager]
layout = [1, 4, 3]
linemode = "mtime"
scrolloff = 8
show_hidden = true
show_symlink = true
sort_by = "alphabetical"
sort_dir_first = true
sort_reverse = false
sort_sensitive = false

[preview]
max_height = 1000
max_width = 1000
tab_size = 2

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
