{
  imports = [
    ./auto-session.nix
    ./bufferline.nix
    ./cmp.nix
    ./format.nix
    ./lazygit.nix
    ./lint.nix
    ./lsp.nix
    ./lualine.nix
    ./lz-n.nix
    ./noice.nix
    ./supermaven.nix
    ./telescope.nix
    ./treesitter.nix
    ./trouble.nix
    ./which-key.nix
    ./yazi.nix
  ];
}
